### ISSUE TITLE
SQLAlchemy IntegrityError when trying to load data to database without events

### ISSUE THREAD

**Issue by T0SH1R0** [uralbash/sqlalchemy_mptt#52]
Hey. Nice module.

I'm trying to load a huge amount of data into PostgreSQL via SQLAlchemy, and I want to use it with MPTT, so I searched and found your module. But I got stuck with a problem.

Here's my model:
```
from sqlalchemy_mptt.mixins import BaseNestedSets
from app import db

class MyModelTree(db.Model, BaseNestedSets):
    __tablename__ = "my_model_tree"
    id = db.Column(db.Integer, primary_key=True)
    code = db.Column(db.String(100), index=True, unique=True)
    name = db.Column(db.String(512), index=True)
    code_parent = db.Column(db.String(100), index=True)
```

And here's a part of my upload to database script:
```
from sqlalchemy_mptt import tree_manager
...
for event, element in etree.iterparse(filepath, tag="XML_ObjectFields"):
    item = models.MyModelTree()
    item.code = element.find('code').text
    item.name = element.find('name').text
    if element.find('code_parent') is not None:
        item.code_parent = element.find('code_parent').text
        parent = models.MyModelTree.query.filter_by(code=element.find('code_parent').text).first()
        if parent:
            item.parent_id = parent.id
    db.session.add(item)
    element.clear()
db.session.commit()
...
tree_manager.register_events()
```
And here's the error:
```
Traceback (most recent call last):
  File "upload_data.py", line 48, in <module>
    parent = models.MyModelTree.query.filter_by(code=element.find('code_parent').text).first()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2634, in first
    ret = list(self[0:1])
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__
    return list(res)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2735, in __iter__
    self.session._autoflush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1303, in _autoflush
    util.raise_from_cause(e)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 1293, in _autoflush
    self.flush()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 139, in save_obj
    save_obj(base_mapper, [state], uowtransaction, single=True)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) null value in column "rgt" violates not-null constraint
DETAIL:  Failing row contains (1, 00000000000, ╨Ю╨▒╤К╨╡╨║╤В╤Л ╨░╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╕╨▓╨╜╨╛-╤В╨╡╤А╤А╨╕╤В╨╛╤А╨╕..., null, null, null, 0, null, null).
 [SQL: 'INSERT INTO my_model_tree (code, name, code_parent, rgt, lft, level, parent_id, tree_id) VALUES (%(code)s, %(name)s, %(code_parent)s, %(rgt)s, %(lft)s, %(level)s, %(parent_id)s, %(tree_id)s) RETURNING my_model_tree.id'] [parameters: {'code': '00000000000', 'rgt': None, 'name': u'\u041e\u0431\u044a\u0435\u043a\u0442\u044b \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u0438\u0432\u043d\u043e-\u0442\u0435\u0440\u0440\u0438\u0442\u043e\u0440\u0438\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0434\u0435\u043b\u0435\u043d\u0438\u044f,^ \u043a\u0440\u043e\u043c\u0435 \u0441\u0435\u043b\u044c\u0441\u043a\u0438\u0445 \u043d\u0430\u0441\u0435\u043b\u0435\u043d\u043d\u044b\u0445 \u043f\u0443\u043d\u043a\u0442\u043e\u0432', 'parent_id': None, 'level': 0, 'lft': None, 'code_parent': None, 'tree_id': None}]
```
Seems like it does not generate rgt/lft values when events are off. Should I set them to any random number instead? Cause I will rebuild the tree after I finish uploading all data anyways. Or is there any other way to first insert all the data, and only then count mptt-tree values?

Thanx

**P.S:** Do I rebuild values like this?
`models.MyModelTree.rebuild_tree(db.session, models.MyModelTree.tree_id)`

**Comment by uralbash** [comment]
In your case, these settings will be extra, try to remove them:
```python
from sqlalchemy_mptt import tree_manager
...
tree_manager.register_events()
```

**Comment by T0SH1R0** [comment]
> In your case, these settings will be extra, try to remove them:
> ```
> from sqlalchemy_mptt import tree_manager
> ...
> tree_manager.register_events()
> ```

It worked somehow, but it means that the tree is reconstructed after every insert, isn't it?

Also, I did not find much in documentation about **path_to_root()** method. When i'm trying to get a dict with path from some node to root, it gives me an SQL code instead of executing it and returning a dict:
```
for mt in models.MyModelTree.query.all():
    if mt.parent_id:
        breadcrumbs = mt.path_to_root()
        print str(breadcrumbs)
```
```
SELECT * FROM my_model_tree
WHERE my_model_tree.tree_id = :tree_id_1 AND 
            my_model_tree.lft <= :lft_1 AND 
            my_model_tree.rgt >= :rgt_1 
ORDER BY my_model_tree.tree_id DESC, 
                my_model_tree.level DESC, 
                my_model_tree.lft DESC
...
```

**Comment by uralbash** [comment]
Well, when you add any data to the database, he tries to be counted ``lft``, ``rgt`` and ``level`` attribute. This is done very quickly if the tree already exists in the database, but it is absolutely not allowed for initialize the tree, it is very long. In your case, you can change the code like this:

```python
from sqlalchemy_mptt import tree_manager
...

tree_manager.register_events(remove=True) # Disable events

for event, element in etree.iterparse(filepath, tag="XML_ObjectFields"):
    item = models.MyModelTree()
    item.code = element.find('code').text
    item.name = element.find('name').text
    if element.find('code_parent') is not None:
        item.code_parent = element.find('code_parent').text
        parent = models.MyModelTree.query.filter_by(code=element.find('code_parent').text).first()
        if parent:
            item.parent_id = parent.id
    db.session.add(item)
    element.clear()
db.session.commit()
...
tree_manager.register_events() # enabled events back
 models.MyModelTree.rebuild_tree(db.session, models.MyModelTree.tree_id) # rebuild lft, rgt value automatically
```

Also see tests for example https://github.com/uralbash/sqlalchemy_mptt/blob/master/sqlalchemy_mptt/tests/test_events.py#L57-L90

> Also, I did not find much in documentation about path_to_root() method. When i'm trying to get a dict with path from some node to root, it gives me an SQL code instead of executing it and returning a dict:

Most methods return Query object, like this https://github.com/uralbash/sqlalchemy_mptt/blob/master/sqlalchemy_mptt/mixins.py#L208
Therefore, simply complete the construction of the query, like ``.all()`` method:
```python
for mt in models.MyModelTree.query.all():
    if mt.parent_id:
        breadcrumbs = mt.path_to_root()
        print str(breadcrumbs.all())
```

Documentation that is not good enough. I will be glad to any contribute there.

**Comment by uralbash** [comment]
@T0SH1R0 Please tell me if this solve your problem?

**Comment by uralbash** [comment]
I added the documentation here http://sqlalchemy-mptt.readthedocs.io/initialize.html#filling-data-at-the-first-time
